{% set data = load_setuptools() %}

package:
  name: mplview
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/jakirkham/mplview.git
  git_rev: 46812ecf3a480eab3b3ec365c18d64b8d7fdc02b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - npctypes

test:
  source_files:
    - tests

  imports:
    - mplview

  commands:
    - python -m unittest discover -s .

about:
  home: https://github.com/jakirkham/mplview
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple, embeddable Matplotlib-based image viewer.
  doc_url: https://mplview.readthedocs.io/
  dev_url: https://github.com/jakirkham/mplview

extra:
  recipe-maintainers:
    - jakirkham
