travis:
  secure:
    BINSTAR_TOKEN: RXCGrQiMliZCKr8mp/VDwSQMjt4KJYbBDNlJwGkGSAn0TalzdbBUs7wNwHD0lAG0chG07/1x6x60CPnWDTDC5X/XO467RNxbhim/JSm3F/fO2StAXZ2o57c94BTo+bqw0Vhcp4rmhAhFzxZ8GXrK45glb7JcciJlxLvxzstHT+6zxUy1/ihU+Swl90Uc9EaAKF8azakf0v+STIo0jt/WtQZmK9I/5nv7ENvrkAYvsZCRJCXp0nsNiL8bKfSfWnUWxqZxt+4F3E6YlnjUCC9+k4QMQlOPNjl0Fz486HFRAadZ7sxTpJv+JFBWHuzPad7C4rEqiT5L9Nnl0v6O24BaoXXGMh+79DkvE7RmexmjGRNN9y6TEJ2b4ovgp5XLmwLdqJGculk0b4fEpitdlKtkUPiLiG5hBtfFylCKB1Xm5fCUW4sDXk3aVPcUkFCVsEwUwe+KCV4AR8Qh/ODcUAPZs+z++oD728Iua9WhWnyaV+cbAGBpDYz1T4QPk2Oh95wif4MrWy+ak4UIAhg4C2F35qGjSXy2hrnwEt67QxdCNCrpxXSArfl4GdzfGZquvgBjz770EQ7+VJy8uF/KFSXd9cxVBEJyiLE+QDLeQ2dS4DLD6XmIsjtnhiWgkz8+F0kcXmWbgTBM/qhXtccNBlbVjvBaXvyzubHLFPHGaNlM0W0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
