travis:
  secure:
    BINSTAR_TOKEN: LmEsCA0MmjFv5WjAPs9hkky6fjeZjS0xhQ6mYYSJP0nVd5jCcfWTkZc0BjW7Ay9CCS3QWblzYlneoc3XZCtacLiy4lQAKiQyD3IZpzQVrk/FblAYM5K1XNiDfSSmPY4vLtLhvB26gP0Scie2d46I3O3v/jk9kJ+EUGWcHox1U8EeeCw+NDETbA3vHp6xdr+FUw0wWetIi1yJnRbeDoAAH0HYc047AssLbhZ0USWd/yCwZq51vk0CLejh5pzVcoMYhn3K98ZiQLCYoCnTZ0kt12HZvH4t5SykrXvsDrz3ftKnnrvcoa9mtJB59n8wLedumILzeROBwn1LaYvH/Us+RcvYRzni45kr+1FAivfND17IwEz6rEOtuNxxtWjnCSZiF4mvSq+M9+kciS8h+JGdIy72OQg907GYkuD6yYmnsWPxjHfXiHR+BPgOTwpw0Lk6ZVbJHruvc0EgAlzR08/nL885y4uhQUODD5/XWN0SZQPgrYKVU+Sfrxjt8TP01w3CCBxPy/I57fH0xBPnTwJ8fcWenfWoOQLgLlQf/sTDVwZMe5er8y+5IlVl4PVrqpbMZHXR85+lt2iWC+IKJf2sUu/mO8phub0iPwf9BO3sfAyrbgOuPWb49j+gjzyc73MVanw9sCVkGvT4Zx36qaZskwcgJ9V+MLJN8y9IeJJs/bk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
