travis:
  secure:
    BINSTAR_TOKEN: GgF2d+tHK9A7YnAX+eSNH8xO1N89OMmA6FAxgDtACFIXHtW6lzBhYyU06sm1I5Gu+GpVU4hH+jNzy3zJeUdceXSTl96CwtE0xvAYSVebhWdk5vbJYmDV49ULJ9ChhuKQieafZVLCtghHyXSFwVWE2+iTTr1WyOU+c3Ma+B6R27h68TLmVqikGhW70u3sXGlU6Uw/vtI8eVnEshfeBFtZk56/AJB3klMovENK0aFBrdw1sJm1ScqzvcBkphjoVLvFkuOIWjXNuKX3pQeLyBw4t1TPxt0U897vJ35H/AoAIkMvc+ueANLZGf2gXX0oN960ES9P+nOmBbnVLxf6HiW3F9iV2OEHyhmhpXqY1TNa30yevpt0qlFCz4sHk3thKz2Ne8xN2LM6OyaNSC/nfFjr+TiQ5giSQmFPCdLj8LLBNhMr0W0biph8q/ndMu0WUjus55lcLHACSBAjbysLkrFcj9JPAOPDhMrMMBHFMDczbSpB4l2vhAmqwJBOHMYjRQQKxeC+1h50+x29Il/7S5rz0e57f13kiX2WF5gC61NgWizqNHdGCMTFWaepevf2T3D77WACKEsOwJGSAPux/QlfSoqAtSLbKuQfHjIGBUtr8pFs22Rd+HSqAthazkQK54KEW0SWCSNUDdLjYpU3tT7bG+AyH0xmRA7cW/2rKZTe/Ug=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
